### ISSUE TITLE
docker-compose.yml should be fixed for Windows

### ISSUE THREAD

**Issue by dominikbraun** [EwanValentine/shippy-service-vessel#2]
Hi,

so when running the current `docker-compose.yml` file, the `datastore` service cannot be started due to [this error](https://stackoverflow.com/questions/54911021/unable-to-start-docker-mongo-image-on-windows). This can be fixed by explicitly creating a named volume for the datastore:

```yaml
version: "3.7"

services:

  # ...

  datastore:
    image: mongo:4.2.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongodata:/data/db
    networks:
      - consignment-tier
    ports:
      - 27017

# ...

volumes:
  mongodata:
```

I changed `- ./data/db:/data/db` to ` - mongodata:/data/db` and added the `volumes` section. That fixes the error.
